### ISSUE TITLE
How to make OPNet have the exact setup as CATER?

### ISSUE THREAD

**Issue by hongluzhou** [ofrikleinfeld/ObjectPermanence#1]
Hi,

Thanks for sharing your code! Nice paper and great work! I noticed that in the paper Section 7.3, you reported the performance of OPNet on the original CATER dataset with the exact setup as in the CATER paper, and compared with the baseline results reported by the CATER paper. However, I was confused. If I understood the paper correctly, OPNet will predict the bounding box for the snitch for every frame. The "snitch localization" task from the CATER paper requires a classification prediction, i.e., to predict which grid from the 6x6 grids (which are not pixel grids) is the grid that the snitch was finally localized. I couldn't find how you handled this to have the exact setup as CATER baselines from your paper or code. Could you help me and explain? Thanks!

Best,
Honglu

**Comment by ofrikleinfeld** [comment]
Hi,
Thank you for showing interest in our work.
In Section 7.3 we indeed experimented with the exact setup defined in the CATER paper for the snitch localization task.

Upon your request, we added to the code base another operation mode called "cater_inference". (Please see our modified documenation)
Running this mode will output the 6x6 grid class predictions for each video in the provided dataset (only using the snitch location in the last frame of each video).
We built upon the CATER code base (see https://github.com/rohitgirdhar/CATER) and computed the class predictions using the same tranformation defined in their implementation.

In order to fully reproduce the results repored in Section 7.3 you need the perfrom the following:
1. Download the original CATER dataset
2. Run an object detection model on it, as a preprocessing stage (resulting in bounding box predictions for each object in each frame, for each video in the dataset)
3. Run our model as described in the documentation
4. Compare the class labels with the class predictions to compute accuracy and L1 distance

Hope this helps.
Best,
Ofri

**Comment by hongluzhou** [comment]
Hi Ofri,

This is very helpful! Thank you so much for replying and updating the code!!

Have a great week!

Best,
Honglu
